/**
 * Mock OpenAI client that simulates API response time and generates mock responses
 */
export class MockOpenAIClient {
  /**
   * Simulates OpenAI API call with delay and returns a mock response
   */
  async generateAnswer(question: string): Promise<{ answer: string; tokens: number }> {
    // Simulate API delay (500-1500ms)
    const delay = Math.floor(Math.random() * 1000) + 500;
    await new Promise((resolve) => setTimeout(resolve, delay));

    // Generate mock answer
    const answer = `This is a mocked OpenAI response to your question: "${question}". In a real implementation, this would be generated by GPT models.`;

    // Estimate tokens (rough approximation: ~4 characters per token)
    const questionTokens = Math.ceil(question.length / 4);
    const answerTokens = Math.ceil(answer.length / 4);
    const tokens = questionTokens + answerTokens + 10; // Add some overhead

    return { answer, tokens };
  }
}
